### ISSUE TITLE
%Stream.Interval{}

### ISSUE THREAD

**Issue by hamiltop** [hamiltop/streamz#18]
Make Stream.interval return a Struct.

``` elixir
iex> Stream.interval(1000)
%Stream.Interval{time: 1000, count: :infinity}
iex> Stream.once(1000)
%Stream.Interval{time: 1000, count: 1}
```

Random idea: Any way to make:

``` elixir
iex> Stream.interval(1000) |> Stream.take(10)
%Stream.Interval{time: 1000, count: 10}
```

Or maybe that should just be:

``` elixir
iex> Stream.interval(1000, 10)
%Stream.Interval{time: 1000, count: 10}
```

**Comment by josevalim** [comment]
IIRC the idea for making it a struct is so that we could implement Connectable for it.

**Comment by hamiltop** [comment]
Yes, the reason was that for Connectable we would use the :timer server instead. We abandoned this idea, so this is probably obsolete.
